### ISSUE TITLE
`foreach` formatting doesn't obey `line_length`

### ISSUE THREAD

**Issue by mikedld** [MaciejPatro/cmake-tidy#145]
Input:
```cmake
foreach(X aa bb cc dd ee ff gg hh ii jj kk ll mm nn oo pp qq rr ss tt uu vv ww xx yy zz)
    message("${X}")
endforeach()
```
Config:
```json
{
  "tabs_as_spaces": true,
  "tab_size": 2,
  "line_length": 60
}
```
Expected output:
```cmake
foreach(X aa bb cc dd ee ff gg hh ii jj kk ll mm nn oo pp qq
          rr ss tt uu vv ww xx yy zz)
  message("${X}")
endforeach()

# or

foreach(X
    aa
    bb
    cc
    # ...
    xx
    yy
    zz)
  message("${X}")
endforeach()

# or (if refactoring is allowed)

foreach(X
    IN ITEMS
      aa
      bb
      cc
      # ...
      xx
      yy
      zz)
  message("${X}")
endforeach()

# or...
```
Actual output: same as input

Side note: `RANGE` and `IN {ITEMS,LISTS,ZIP_LISTS}` variants need to be considered as well.

**Comment by MaciejPatro** [comment]
Thank you for the input!

I would go for the approach of:
```cmake
foreach(X
    aa
    bb
    cc
    # ...
    xx
    yy
    zz)
  message("${X}")
endforeach()
```

The reason for it is mainly that I'm still in a process of figuring out how I would like to handle line-breaking in more general way for similar cases to:

```cmake
foreach(X aa bb cc dd ee ff gg hh ii jj kk ll mm nn oo pp qq
          rr ss tt uu vv ww xx yy zz)
  message("${X}")
endforeach()
```

Regarding the refactored case with `IN ITEMS`: this is a great point, but I would like to keep `formatting` and `refactoring` as 2 separate steps/subcommands as they have different concerns for me. For that reason I've opened #147 issue to track this change.
